name: Publish Python Package

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  upload-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python3 setup.py build_py
          python3 setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          OUTPUT=$(python3 -m twine upload --verbose dist/* 2>&1) || true
          if echo "$OUTPUT" | grep -q "File already exists"; then
            echo "Package version already exists. Skipping further steps."
            exit 0
          fi
          echo "$OUTPUT"
